version: "3.9"

services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: resq_postgres
    restart: always
    environment:
      POSTGRES_DB: resq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d resq"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    container_name: resq_api
    build:
      context: .
      dockerfile: RESQ.Presentation/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: >
        Host=postgres;
        Port=5432;
        Database=resq;
        Username=postgres;
        Password=12345
    ports:
      - "5000:8080"

volumes:
  postgres_data:
